---
config:
  theme: default
---
gantt
    title ESRS Milestones 
    dateFormat  YYYY-MM-DD
    axisFormat  %d %b
    tickInterval 1week

    %% Week 4
    W4-IRv1  :a1, 2026-02-16, 1w
    W4-REND  :a2, 2026-02-16, 1w
    W4-SQL   :a3, 2026-02-16, 1w
    W4-CI    :a4, 2026-02-16, 1w

    %% Week 5
    W5-DB    :a5, 2026-02-23, 1w
    W5-ED    :a6, 2026-02-23, 1w
    W5-HANK  :a7, 2026-02-23, 1w

    %% Week 6
    W6-MD2IR :a8, 2026-03-02, 1w

    %% Weeks 7-8
    W7-8-H2IR :a9, 2026-03-09, 2w

    %% Spring Break
    BREAK   :crit, b1, 2026-03-23, 3w

    %% Week 9
    W9-MD   :a10, 2026-04-13, 1w

    %% Weeks 9-11 (Stretch Window)
    W9-11-ACC   :a11, 2026-04-13, 3w
    W9-11-OTH   :a12, 2026-04-13, 3w
    W9-11-ENHC  :a13, 2026-04-13, 3w
